name: w_module
version: 0.1.0
dependencies:
dev_dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  coverage:
    git:
      url: https://github.com/ekweible/coverage.git
      ref: 796a265
  dart_codecov_generator:
    git:
      url: https://github.com/ekweible/dart_codecov_generator.git
      ref: 0.3.0
  dart_style: '>=0.1.8 <0.2.0'
  mockito: '>=0.10.0 <0.11.0'
  test: '0.12.2'
  w_flux:
    path: ../w_flux/
  web_skin_react:
    git:
      url: git@github.com:Workiva/web-skin-react.git
      ref: 2.1.4
