name: w_module
version: 0.3.1
description: Base module classes with a well defined lifecycle for modular Dart applications.
authors:
  - Workiva Client Platform Team <team-clientplatform@workiva.com>
  - Dustin Lessard <dustin.lessard@workiva.com>
  - Evan Weible <evan.weible@workiva.com>
  - Jay Udey <jay.udey@workiva.com>
  - Max Peterson <maxwell.peterson@workiva.com>
  - Trent Grover <trent.grover@workiva.com>
homepage: https://github.com/Workiva/w_module
dev_dependencies:
  browser: "^0.10.0+2"
  browser_detect: "^1.0.3"
  coverage: "^0.7.2"
  dart_dev: "^1.0.0"
  dart_style: "^0.2.0"
  dartdoc: ">=0.4.0 <0.7.0"
  mockito: "^0.10.0"
  react: ">=0.5.0 <0.8.0"
  source_gen: "^0.4.2"
  test: "^0.12.0"
  w_flux: "^1.0.0"
environment:
  sdk: ">=1.9.0 <2.0.0"
